version: "3.9"

services:
  web:
    build: .
    container_name: biblionet_v3_web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      # sobreescribir .env dentro del container
      DB_HOST: host.docker.internal


# Servicio para ejecutar los tests de Django
  tests:
    build: . # Usa el mismo Dockerfile que 'web' para tener el entorno Python/Django
    container_name: biblionet_v3_tests
    # Comando est치ndar de Django para correr todos los tests
    command: python manage.py test
    volumes:
      - .:/app # Monta el c칩digo fuente, incluyendo la carpeta de tests
    env_file:
      - .env
    environment:
      # Reusa DB_HOST para que los tests puedan encontrar la base de datos
      DB_HOST: host.docker.internal
    # Si la base de datos local est치 activa, depende de ella:
    # Si la DB est치 en un contenedor, debes descomentar 'db' abajo y esta dependencia:
    # depends_on:
    #   - db
    
  # docker default sin usar base local
  # db:
  #   image: mysql:8.0
  #   container_name: biblionet_v3_db
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: ${DB_NAME}
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_ROOT_PASSWORD: root
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - db_data:/var/lib/mysql

#volumes:
#  db_data:
