version: "3.9"

services:
  web:
    build: .
    container_name: biblionet_v3_web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      # sobreescribir .env dentro del container
      DB_HOST: host.docker.internal

  # docker default sin usar base local
  # db:
  #   image: mysql:8.0
  #   container_name: biblionet_v3_db
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: ${DB_NAME}
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_ROOT_PASSWORD: root
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - db_data:/var/lib/mysql

#volumes:
#  db_data:
